# Generated by Django 3.2.9 on 2021-12-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeCode', models.IntegerField(primary_key=True, serialize=False)),
                ('officeName', models.CharField(max_length=20)),
                ('attribution', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('orgCode', models.IntegerField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=120)),
                ('dateJoined', models.DateField()),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=12)),
                ('zip', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceCode', models.IntegerField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=80)),
                ('premium', models.FloatField()),
                ('allocation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriberID', models.IntegerField(primary_key=True, serialize=False)),
                ('requestDate', models.DateField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('motifCancel', models.CharField(max_length=120)),
                ('serviceCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subscriptionTypeCode', models.IntegerField(primary_key=True, serialize=False)),
                ('subscriptionTypeName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20, null=True)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=12)),
                ('zip', models.CharField(max_length=11)),
                ('employerName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('transferID', models.IntegerField(primary_key=True, serialize=False)),
                ('transferFrom', models.CharField(max_length=40)),
                ('transferTo', models.CharField(max_length=40)),
                ('requestDate', models.DateField()),
                ('transferDate', models.DateField(null=True)),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriptionTypeCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('nativeCountry', models.CharField(max_length=20)),
                ('citizenship', models.CharField(max_length=20)),
                ('isDelegate', models.BooleanField()),
                ('orgCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.organization')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('officeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
    ]
